/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.epayment.views;

/**
 *
 * @author ramesesinc
 */
public class EORListQueryPanel extends javax.swing.JPanel {

    /**
     * Creates new form EORListQueryPanel
     */
    public EORListQueryPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xLabel1 = new com.rameses.rcp.control.XLabel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        setLayout(new com.rameses.rcp.control.layout.XLayout());

        xLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        xLabel1.setText("Partner");
        add(xLabel1);

        xComboBox1.setCaption("Partner ");
        xComboBox1.setExpression("#{ item.objid } - #{item.name }");
        xComboBox1.setItems("partnerList");
        xComboBox1.setName("partner"); // NOI18N
        xComboBox1.setEmptyText("--");
        add(xComboBox1);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XLabel xLabel1;
    // End of variables declaration//GEN-END:variables
}
