/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.epayment.views;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author elmonazareno
 */
@Template(FormPage.class)
@StyleSheet
public class EORManualPostPage extends javax.swing.JPanel {

    /**
     * Creates new form ManualPostEORPage
     */
    public EORManualPostPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xDecimalField1 = new com.rameses.rcp.control.XDecimalField();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        jScrollPane1 = new javax.swing.JScrollPane();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        xButton1 = new com.rameses.rcp.control.XButton();

        xTextField1.setCaption("Payment Order No");
        xTextField1.setName("entity.paymentorderno"); // NOI18N
        xTextField1.setCaptionWidth(200);
        xTextField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField1.setRequired(true);
        xFormPanel1.add(xTextField1);

        xDecimalField1.setCaption("Amount");
        xDecimalField1.setName("entity.amount"); // NOI18N
        xDecimalField1.setCaptionWidth(200);
        xDecimalField1.setRequired(true);
        xFormPanel1.add(xDecimalField1);

        xComboBox1.setCaption("Txn Type");
        xComboBox1.setItemKey("");
        xComboBox1.setItems("txntypes");
        xComboBox1.setName("entity.txntype"); // NOI18N
        xComboBox1.setCaptionWidth(200);
        xComboBox1.setRequired(true);
        xFormPanel1.add(xComboBox1);

        xTextField2.setCaption("Payment Partner Code");
        xTextField2.setName("entity.paymentpartnerid"); // NOI18N
        xTextField2.setCaptionWidth(200);
        xTextField2.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xTextField2.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField2.setRequired(true);
        xFormPanel1.add(xTextField2);

        xTextField3.setCaption("Payment Trace No");
        xTextField3.setName("entity.traceid"); // NOI18N
        xTextField3.setCaptionWidth(200);
        xTextField3.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField3.setRequired(true);
        xFormPanel1.add(xTextField3);

        xDateField1.setCaption("Payment Trace Date");
        xDateField1.setName("entity.tracedate"); // NOI18N
        xDateField1.setCaptionWidth(200);
        xDateField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xDateField1.setRequired(true);
        xFormPanel1.add(xDateField1);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 60));

        xTextArea1.setCaption("Reason");
        xTextArea1.setName("entity.reason"); // NOI18N
        xTextArea1.setCaptionWidth(200);
        xTextArea1.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xTextArea1.setPreferredSize(new java.awt.Dimension(65, 50));
        xTextArea1.setRequired(true);
        jScrollPane1.setViewportView(xTextArea1);

        xFormPanel1.add(jScrollPane1);

        xLabel1.setCaption("Created By");
        xLabel1.setExpression("#{ entity.createdby.name }");
        xLabel1.setVisibleWhen("#{ mode == 'open' }");
        xLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        xLabel1.setCaptionWidth(200);
        xLabel1.setPreferredSize(new java.awt.Dimension(0, 18));
        xFormPanel1.add(xLabel1);

        xLabel2.setCaption("Date Created");
        xLabel2.setExpression("#{ entity.dtcreated }");
        xLabel2.setVisibleWhen("#{ mode == 'open' }");
        xLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        xLabel2.setCaptionWidth(200);
        xLabel2.setDateFormat("yyyy-MM-dd");
        xLabel2.setPreferredSize(new java.awt.Dimension(0, 18));
        xFormPanel1.add(xLabel2);

        xButton1.setCaption("");
        xButton1.setName("submit"); // NOI18N
        xButton1.setVisibleWhen("#{ mode == 'create' }");
        xButton1.setCaptionWidth(200);
        xButton1.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xButton1.setText("Submit");
        xFormPanel1.add(xButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XDecimalField xDecimalField1;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField3;
    // End of variables declaration//GEN-END:variables
}
