/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.epayment.views;

/**
 *
 * @author ramesesinc
 */
public class EORPaymentOrderResolverPage extends javax.swing.JPanel {

    /**
     * Creates new form EORPaymentOrderResolverPage
     */
    public EORPaymentOrderResolverPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        xButton4 = new com.rameses.rcp.control.XButton();
        xButton1 = new com.rameses.rcp.control.XButton();
        xButton2 = new com.rameses.rcp.control.XButton();
        xButton3 = new com.rameses.rcp.control.XButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();

        setPreferredSize(new java.awt.Dimension(713, 495));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel1.setLayout(new com.rameses.rcp.control.layout.YLayout());

        xLabel1.setExpression("<html>You have selected items need to be resolved. Please click the <font color=\"green\"><b>Start</b></font> button to begin the process.</html>");
        xLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 20, 10));
        xLabel1.setFontStyle("font-size: 14;");
        xLabel1.setUseHtml(true);
        jPanel1.add(xLabel1);

        xPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 10, 5));
        xPanel1.setPreferredSize(new java.awt.Dimension(704, 45));
        com.rameses.rcp.control.layout.XLayout xLayout1 = new com.rameses.rcp.control.layout.XLayout();
        xLayout1.setSpacing(5);
        xPanel1.setLayout(xLayout1);

        xButton4.setName("_close"); // NOI18N
        xButton4.setVisibleWhen("#{runlevel==0}");
        xButton4.setText("Close");
        xPanel1.add(xButton4);

        xButton1.setName("doStart"); // NOI18N
        xButton1.setVisibleWhen("#{runlevel==0}");
        xButton1.setText("Start");
        xPanel1.add(xButton1);

        xButton2.setName("doStop"); // NOI18N
        xButton2.setVisibleWhen("#{runlevel==1}");
        xButton2.setText("Stop");
        xPanel1.add(xButton2);

        xButton3.setDisableWhen("#{1==1}");
        xButton3.setVisibleWhen("#{runlevel==2}");
        xButton3.setText("Stopping...");
        xPanel1.add(xButton3);

        jPanel1.add(xPanel1);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        xTextArea1.setHandler("logHandler");
        xTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        xTextArea1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        xTextArea1.setReadonly(true);
        jScrollPane1.setViewportView(xTextArea1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XButton xButton3;
    private com.rameses.rcp.control.XButton xButton4;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XPanel xPanel1;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    // End of variables declaration//GEN-END:variables
}
