/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.epayment.views;

import com.rameses.osiris2.themes.CloseOnlyPage;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author elmonazareno
 */
@Template(CloseOnlyPage.class)
public class ErrorMsgPage extends javax.swing.JPanel {

    /**
     * Creates new form ErrorMsgPage
     */
    public ErrorMsgPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xTabbedPane1 = new com.rameses.rcp.control.XTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();
        jPanel1 = new javax.swing.JPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        xLabel3 = new com.rameses.rcp.control.XLabel();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        xLabel5 = new com.rameses.rcp.control.XLabel();
        xLabel6 = new com.rameses.rcp.control.XLabel();
        xLabel7 = new com.rameses.rcp.control.XLabel();
        xLabel8 = new com.rameses.rcp.control.XLabel();
        xLabel14 = new com.rameses.rcp.control.XLabel();
        xLabel15 = new com.rameses.rcp.control.XLabel();
        xLabel9 = new com.rameses.rcp.control.XLabel();
        xLabel10 = new com.rameses.rcp.control.XLabel();
        xLabel13 = new com.rameses.rcp.control.XLabel();
        xLabel11 = new com.rameses.rcp.control.XLabel();
        xLabel12 = new com.rameses.rcp.control.XLabel();

        setPreferredSize(new java.awt.Dimension(550, 445));
        setLayout(new java.awt.BorderLayout());

        xTextArea1.setEditable(false);
        xTextArea1.setName("entity.errdetail"); // NOI18N
        jScrollPane1.setViewportView(xTextArea1);

        xTabbedPane1.addTab("Details", jScrollPane1);

        xLabel1.setCaption("Payment Ref");
        xLabel1.setExpression("#{ po.objid }");
        xLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel1.setCaptionWidth(150);
        xLabel1.setPreferredSize(new java.awt.Dimension(0, 18));
        xFormPanel1.add(xLabel1);

        xLabel2.setCaption("Txn Type");
        xLabel2.setExpression("#{ po.txntype } - #{ po.txntypename }");
        xLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel2.setCaptionWidth(150);
        xLabel2.setPreferredSize(new java.awt.Dimension(0, 18));
        xFormPanel1.add(xLabel2);

        xLabel3.setCaption("Txn Ref No");
        xLabel3.setExpression("#{ po.refno }");
        xLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel3.setCaptionWidth(150);
        xLabel3.setPreferredSize(new java.awt.Dimension(0, 18));
        xFormPanel1.add(xLabel3);

        xLabel4.setCaption("Particulars");
        xLabel4.setExpression("#{ po.particulars }");
        xLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel4.setCaptionWidth(150);
        xLabel4.setPreferredSize(new java.awt.Dimension(0, 18));
        xFormPanel1.add(xLabel4);

        xLabel5.setCaption("Paid By");
        xLabel5.setExpression("#{ po.paidby }");
        xLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel5.setCaptionWidth(150);
        xLabel5.setPreferredSize(new java.awt.Dimension(0, 18));
        xFormPanel1.add(xLabel5);

        xLabel6.setCaption("Paid By Address");
        xLabel6.setExpression("#{ po.paidbyaddress }");
        xLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel6.setCaptionWidth(150);
        xLabel6.setPreferredSize(new java.awt.Dimension(0, 18));
        xFormPanel1.add(xLabel6);

        xLabel7.setCaption("Amount");
        xLabel7.setExpression("#{ po.amount }");
        xLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel7.setCaptionWidth(150);
        xLabel7.setNumberFormat("#,##0.00");
        xLabel7.setPreferredSize(new java.awt.Dimension(0, 18));
        xFormPanel1.add(xLabel7);

        xLabel8.setCaption("Expiry Date");
        xLabel8.setExpression("#{ po.expirydate }");
        xLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel8.setCaptionWidth(150);
        xLabel8.setDateFormat("yyyy-MM-dd");
        xLabel8.setNumberFormat("#,##0.00");
        xLabel8.setPreferredSize(new java.awt.Dimension(0, 18));
        xFormPanel1.add(xLabel8);

        xLabel14.setCaption("Contact Email");
        xLabel14.setExpression("#{ po.email }");
        xLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel14.setCaptionWidth(150);
        xLabel14.setNumberFormat("#,##0.00");
        xLabel14.setPreferredSize(new java.awt.Dimension(0, 18));
        xFormPanel1.add(xLabel14);

        xLabel15.setCaption("Contact Mobile No");
        xLabel15.setExpression("#{ po.mobileno }");
        xLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel15.setCaptionWidth(150);
        xLabel15.setNumberFormat("#,##0.00");
        xLabel15.setPreferredSize(new java.awt.Dimension(0, 18));
        xFormPanel1.add(xLabel15);

        xLabel9.setCaption("EOR No");
        xLabel9.setExpression("#{ pmt.receiptno }");
        xLabel9.setVisibleWhen("#{ pmt !=null }");
        xLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel9.setCaptionWidth(150);
        xLabel9.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xLabel9.setNumberFormat("#,##0.00");
        xLabel9.setPreferredSize(new java.awt.Dimension(0, 18));
        xFormPanel1.add(xLabel9);

        xLabel10.setCaption("Receipt Date");
        xLabel10.setExpression("#{ pmt.receiptdate }");
        xLabel10.setVisibleWhen("#{ pmt !=null }");
        xLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel10.setCaptionWidth(150);
        xLabel10.setDateFormat("yyyy-MM-dd");
        xLabel10.setPreferredSize(new java.awt.Dimension(0, 18));
        xFormPanel1.add(xLabel10);

        xLabel13.setCaption("Payment Partner");
        xLabel13.setExpression("#{ pmt.partnerid }");
        xLabel13.setVisibleWhen("#{ pmt !=null }");
        xLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel13.setCaptionWidth(150);
        xLabel13.setDateFormat("yyyy-MM-dd");
        xLabel13.setPreferredSize(new java.awt.Dimension(0, 18));
        xFormPanel1.add(xLabel13);

        xLabel11.setCaption("Partner Ref No");
        xLabel11.setExpression("#{ pmt.traceid }");
        xLabel11.setVisibleWhen("#{ pmt !=null }");
        xLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel11.setCaptionWidth(150);
        xLabel11.setDateFormat("yyyy-MM-dd");
        xLabel11.setPreferredSize(new java.awt.Dimension(0, 18));
        xFormPanel1.add(xLabel11);

        xLabel12.setCaption("Partner Txn Date");
        xLabel12.setExpression("#{ pmt.tracedate }");
        xLabel12.setVisibleWhen("#{ pmt !=null }");
        xLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel12.setCaptionWidth(150);
        xLabel12.setDateFormat("yyyy-MM-dd");
        xLabel12.setPreferredSize(new java.awt.Dimension(0, 18));
        xFormPanel1.add(xLabel12);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addContainerGap())
        );

        xTabbedPane1.addTab("Info", jPanel1);

        add(xTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel10;
    private com.rameses.rcp.control.XLabel xLabel11;
    private com.rameses.rcp.control.XLabel xLabel12;
    private com.rameses.rcp.control.XLabel xLabel13;
    private com.rameses.rcp.control.XLabel xLabel14;
    private com.rameses.rcp.control.XLabel xLabel15;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLabel xLabel3;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XLabel xLabel5;
    private com.rameses.rcp.control.XLabel xLabel6;
    private com.rameses.rcp.control.XLabel xLabel7;
    private com.rameses.rcp.control.XLabel xLabel8;
    private com.rameses.rcp.control.XLabel xLabel9;
    private com.rameses.rcp.control.XTabbedPane xTabbedPane1;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    // End of variables declaration//GEN-END:variables
}
